wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.14.2
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701481292.227985
    t:
      1:
      - 5
      - 8
      - 53
      - 55
      2:
      - 5
      - 8
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.9.18
      5: 0.14.2
      8:
      - 5
